import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Global aesthetics matching KQ_DoiXung style
plt.rcParams['font.sans-serif'] = 'DejaVu Sans'
plt.rcParams['axes.edgecolor'] = '#333333'
plt.rcParams['axes.linewidth'] = 1.0

fig_dir = r'c:\LeDucLuong\HK VII\LuanCuNhan\DeepLearning\Test_Mau\archive\Ket_Qua_V2\KQ_Nen_DX_10seed\figures'
os.makedirs(fig_dir, exist_ok=True)

# EXACTLY 2 MODELS: Baseline and TSVM
models_info = [
    {
        'id': 'Baseline',
        'label': 'Baseline YOLO26s-seg',
        'color': '#1f77b4',
        'dir': r'c:\LeDucLuong\HK VII\LuanCuNhan\DeepLearning\Test_Mau\archive\KetQua_Nen\YOLOv26s-seg'
    },
    {
        'id': 'TSVM',
        'label': 'TSVM (Topology-Shape)',
        'color': '#ff7f0e',
        'dir': r'c:\LeDucLuong\HK VII\LuanCuNhan\DeepLearning\Test_Mau\archive\KetQua_Nen\Kvasir_BG20_YOLO26s_seg_TSVM'
    }
]

print("Loading results.csv for Baseline and TSVM across 10 seeds...")
curves_data = {m['id']: [] for m in models_info}

for m in models_info:
    subdirs = sorted([d for d in glob.glob(os.path.join(m['dir'], '*')) if os.path.isdir(d)])
    for sdir in subdirs:
        csv_file = os.path.join(sdir, 'results.csv')
        if os.path.exists(csv_file):
            df = pd.read_csv(csv_file)
            df.columns = [c.strip() for c in df.columns]
            curves_data[m['id']].append(df)
            
for m in models_info:
    print(f"Model {m['id']}: loaded {len(curves_data[m['id']])} seeds")

# Build summary metrics dynamically from results.csv (single source of truth).
final_metrics = {}
for m in models_info:
    mid = m['id']
    seed_rows = []
    for df in curves_data[mid]:
        if 'metrics/mAP50-95(M)' not in df.columns:
            continue
        idx = df['metrics/mAP50-95(M)'].idxmax()
        row = df.loc[idx]
        seed_rows.append({
            'mask_map50_95': float(row['metrics/mAP50-95(M)']),
            'mask_map50': float(row['metrics/mAP50(M)']),
            'precision': float(row['metrics/precision(M)']),
            'recall': float(row['metrics/recall(M)']),
            'box_map50_95': float(row['metrics/mAP50-95(B)']),
            'val_seg_loss': float(row['val/seg_loss']),
        })
    if len(seed_rows) != 10:
        raise RuntimeError(f"{mid}: expected 10 valid seed results, found {len(seed_rows)}")
    final_metrics[mid] = {}
    for key in ['mask_map50_95','mask_map50','precision','recall','box_map50_95','val_seg_loss']:
        vals = np.array([r[key] for r in seed_rows], dtype=float)
        final_metrics[mid][key] = float(vals.mean())
        final_metrics[mid][f'{key}_std'] = float(vals.std(ddof=1))
    final_metrics[mid]['seeds_mAP'] = [r['mask_map50_95'] for r in seed_rows]
    final_metrics[mid]['seeds_loss'] = [r['val_seg_loss'] for r in seed_rows]

# Confusion-matrix source of truth: verified CSV generated by the package script.
cm_source = os.path.join(os.path.dirname(fig_dir), '01_raw_analysis', 'raw_10seeds_confusion_matrices.csv')
if not os.path.exists(cm_source):
    raise FileNotFoundError(f"Missing canonical confusion-matrix CSV: {cm_source}. Run generate_10seed_thesis_package.py first.")
cm_df = pd.read_csv(cm_source)
for mid in ['Baseline', 'TSVM']:
    part = cm_df[cm_df['model'] == mid].sort_values('seed')
    if len(part) != 10:
        raise RuntimeError(f"{mid}: expected 10 confusion-matrix rows, found {len(part)}")
    for key in ['TP','FN','FP','TN']:
        vals = part[key].to_numpy(dtype=float)
        final_metrics[mid][key] = float(vals.mean())
        final_metrics[mid][f'{key}_std'] = float(vals.std(ddof=1))

# ==============================================================================
# CHART 1: 01_overall_benchmark_barchart.png (2 Models)
# ==============================================================================
plt.figure(figsize=(10, 6.2), dpi=300)
metrics = ['Mask mAP@50-95', 'Mask mAP@50', 'Precision (Mask)', 'Recall (Mask)']
x = np.arange(len(metrics))
width = 0.32

for i, m in enumerate(models_info):
    mid = m['id']
    vals = [
        final_metrics[mid]['mask_map50_95'],
        final_metrics[mid]['mask_map50'],
        final_metrics[mid]['precision'],
        final_metrics[mid]['recall']
    ]
    errs = [
        final_metrics[mid]['mask_map50_95_std'],
        final_metrics[mid]['mask_map50_std'],
        final_metrics[mid]['precision_std'],
        final_metrics[mid]['recall_std']
    ]
    pos = x + (i - 0.5) * width
    rects = plt.bar(pos, vals, width, yerr=errs, capsize=5, label=m['label'], color=m['color'], edgecolor='black', alpha=0.88)
    for rect in rects:
        yval = rect.get_height()
        color_text = '#0f4c81' if mid == 'Baseline' else '#b34700'
        plt.text(rect.get_x() + rect.get_width()/2.0, yval + 0.012, f"{yval:.4f}", ha='center', va='bottom', fontsize=10, fontweight='bold', color=color_text)

plt.title("So Sánh Hiệu Năng Phân Đoạn 10 Seeds (Kvasir_YOLO_SEG_BG20)\nMean ± 1 Std (Baseline vs TSVM)", fontsize=13.5, fontweight='bold', pad=15)
plt.ylabel("Điểm số đo lường (Score)", fontsize=11.5, fontweight='bold')
plt.ylim(0.70, 0.98)
plt.xticks(x, metrics, fontsize=11, fontweight='bold')
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.legend(loc='upper right', frameon=True, fontsize=10.5)
plt.tight_layout()
p1 = os.path.join(fig_dir, '01_overall_benchmark_barchart.png')
plt.savefig(p1)
plt.close()
print("Generated:", p1)

# ==============================================================================
# CHART 2: 02_val_seg_loss_barchart.png (2 Models)
# ==============================================================================
plt.figure(figsize=(7.5, 5.8), dpi=300)
labels = [m['label'] for m in models_info]
losses = [final_metrics[m['id']]['val_seg_loss'] for m in models_info]
loss_errs = [final_metrics[m['id']]['val_seg_loss_std'] for m in models_info]
colors = [m['color'] for m in models_info]

bars = plt.bar(labels, losses, yerr=loss_errs, capsize=7, color=colors, width=0.45, edgecolor='black', alpha=0.88)
# Baseline label
plt.text(bars[0].get_x() + bars[0].get_width()/2.0, losses[0] + 0.04, f"{losses[0]:.4f} ± {loss_errs[0]:.4f}", 
         ha='center', va='bottom', fontsize=10.5, fontweight='bold', color='#0f4c81')
# TSVM label with delta
delta = losses[1] - losses[0]
pct = (delta / losses[0]) * 100
plt.text(bars[1].get_x() + bars[1].get_width()/2.0, losses[1] + 0.04, f"{losses[1]:.4f} ± {loss_errs[1]:.4f}\n(Giảm {abs(pct):.2f}%)", 
         ha='center', va='bottom', fontsize=10.5, fontweight='bold', color='#b34700')

plt.title("Độ Giảm Mất Mát Phân Đoạn (Validation Loss)\nTrung bình 10 Seeds trên tập Kvasir_YOLO_SEG_BG20", fontsize=13, fontweight='bold', pad=15)
plt.ylabel("Validation Loss (Mean ± Std)", fontsize=11, fontweight='bold')
plt.ylim(1.65, 1.86)
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.xticks(fontsize=11, fontweight='bold')
plt.tight_layout()
p2 = os.path.join(fig_dir, '02_val_seg_loss_barchart.png')
plt.savefig(p2)
plt.close()
print("Generated:", p2)

# ==============================================================================
# CHART 3: 03_seed_by_seed_barchart.png (2 Models)
# ==============================================================================
plt.figure(figsize=(13, 6), dpi=300)
seeds = [f"Seed {s}" for s in range(10)]
x = np.arange(10)
width = 0.35

for i, m in enumerate(models_info):
    mid = m['id']
    vals = final_metrics[mid]['seeds_mAP']
    pos = x + (i - 0.5) * width
    rects = plt.bar(pos, vals, width, label=m['label'], color=m['color'], edgecolor='black', alpha=0.88)
    for rect in rects:
        yval = rect.get_height()
        color_text = '#0f4c81' if mid == 'Baseline' else '#b34700'
        plt.text(rect.get_x() + rect.get_width()/2.0, yval + 0.002, f"{yval:.4f}", ha='center', va='bottom', fontsize=7.5, fontweight='bold', rotation=90, color=color_text)

plt.title("Đối Chiếu Hiệu Năng Từng Cặp Seed Độc Lập (Seed 0 - Seed 9)\nMask mAP@50-95 trên tập Kvasir_YOLO_SEG_BG20 (Baseline vs TSVM)", fontsize=13.5, fontweight='bold', pad=15)
plt.ylabel("Mask mAP@50-95", fontsize=11.5, fontweight='bold')
plt.ylim(0.68, 0.76)
plt.xticks(x, seeds, fontsize=10.5, fontweight='bold')
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.legend(loc='lower right', frameon=True, fontsize=10.5)
plt.tight_layout()
p3 = os.path.join(fig_dir, '03_seed_by_seed_barchart.png')
plt.savefig(p3)
plt.close()
print("Generated:", p3)

# ==============================================================================
# CHART 4: 04_convergence_loss_curves.png (2 Models)
# ==============================================================================
epochs = np.arange(1, 101)
fig, axes = plt.subplots(2, 2, figsize=(13, 9.5), dpi=300)
loss_configs = [
    ('val/seg_loss', 'Validation Seg Loss', axes[0, 0]),
    ('train/seg_loss', 'Training Seg Loss', axes[0, 1]),
    ('val/box_loss', 'Validation Box Loss', axes[1, 0]),
    ('val/cls_loss', 'Validation Cls Loss', axes[1, 1])
]

for col_name, title, ax in loss_configs:
    for m in models_info:
        mid = m['id']
        dfs = curves_data[mid]
        if not dfs:
            continue
        mat = np.array([df[col_name].values[:100] for df in dfs if col_name in df and len(df) >= 100])
        if len(mat) > 0:
            mean_c = np.mean(mat, axis=0)
            std_c = np.std(mat, axis=0)
            ax.plot(epochs, mean_c, label=m['label'], color=m['color'], linewidth=2.0)
            ax.fill_between(epochs, mean_c - std_c, mean_c + std_c, color=m['color'], alpha=0.18)
    ax.set_title(title, fontsize=11.5, fontweight='bold')
    ax.set_xlabel("Epoch", fontsize=10)
    ax.set_ylabel("Loss", fontsize=10)
    ax.grid(True, linestyle='--', alpha=0.4)
    ax.legend(fontsize=9.5, loc='upper right')

plt.suptitle("Đường Cong Hội Tụ Các Hàm Mất Mát (Loss Convergence Curves)\nTrung Bình ± 1 Std qua 10 Seeds (Baseline vs TSVM, 100 Epochs)", fontsize=13.5, fontweight='bold', y=0.99)
plt.tight_layout()
p4 = os.path.join(fig_dir, '04_convergence_loss_curves.png')
plt.savefig(p4)
plt.close()
print("Generated:", p4)

# ==============================================================================
# CHART 5: 05_metric_curves_mAP.png (2 Models)
# ==============================================================================
fig, axes = plt.subplots(1, 2, figsize=(13, 5.2), dpi=300)
metric_configs = [
    ('metrics/mAP50-95(M)', 'Mask mAP@50-95 vs Epoch', axes[0]),
    ('metrics/mAP50(M)', 'Mask mAP@50 vs Epoch', axes[1])
]

for col_name, title, ax in metric_configs:
    for m in models_info:
        mid = m['id']
        dfs = curves_data[mid]
        if not dfs:
            continue
        mat = np.array([df[col_name].values[:100] for df in dfs if col_name in df and len(df) >= 100])
        if len(mat) > 0:
            mean_c = np.mean(mat, axis=0)
            std_c = np.std(mat, axis=0)
            ax.plot(epochs, mean_c, label=m['label'], color=m['color'], linewidth=2.0)
            ax.fill_between(epochs, mean_c - std_c, mean_c + std_c, color=m['color'], alpha=0.18)
    ax.set_title(title, fontsize=11.5, fontweight='bold')
    ax.set_xlabel("Epoch (1 -> 100)", fontsize=10)
    ax.set_ylabel("Score", fontsize=10)
    ax.grid(True, linestyle='--', alpha=0.4)
    ax.legend(fontsize=9.5, loc='lower right')

plt.suptitle("Động Thái Phát Triển Độ Chính Xác Phân Đoạn Theo Epoch (10 Seeds, Baseline vs TSVM)", fontsize=13.5, fontweight='bold', y=0.99)
plt.tight_layout()
p5 = os.path.join(fig_dir, '05_metric_curves_mAP.png')
plt.savefig(p5)
plt.close()
print("Generated:", p5)

# ==============================================================================
# CHART 6: 09_metric_stability_band_area.png (2 Models)
# ==============================================================================
plt.figure(figsize=(10, 5.8), dpi=300)
for m in models_info:
    mid = m['id']
    dfs = curves_data[mid]
    col_name = 'metrics/mAP50-95(M)'
    mat = np.array([df[col_name].values[:100] for df in dfs if col_name in df and len(df) >= 100])
    if len(mat) > 0:
        mean_c = np.mean(mat, axis=0)
        min_c = np.min(mat, axis=0)
        max_c = np.max(mat, axis=0)
        plt.fill_between(epochs, min_c, max_c, color=m['color'], alpha=0.22, label=f"Dải phân bổ {m['label']} [Min, Max]")
        plt.plot(epochs, mean_c, color=m['color'], linewidth=2.2, label=f"{m['label']} (Mean)")

plt.title("Biểu Đồ Miền Bao Phủ Độ Ổn Định (Stability Envelope Band)\nBiên Độ Dao Động Cực Đại - Cực Tiểu Giữa 10 Seeds (Baseline vs TSVM)", fontsize=13, fontweight='bold', pad=15)
plt.xlabel("Epoch Huấn Luyện (1 -> 100)", fontsize=11, fontweight='bold')
plt.ylabel("Mask mAP@50-95 Span", fontsize=11, fontweight='bold')
plt.grid(True, linestyle='--', alpha=0.4)
plt.legend(loc='lower right', frameon=True, fontsize=10)
plt.tight_layout()
p6 = os.path.join(fig_dir, '09_metric_stability_band_area.png')
plt.savefig(p6)
plt.close()
print("Generated:", p6)

# ==============================================================================
# CHART 7: 10_radar_multiobjective_tradeoff.png (2 Models)
# ==============================================================================
categories = ['Mask mAP50-95', 'Mask mAP50', 'Precision', 'Recall', 'Stability (1/Var)', 'Loss Opt (1/Loss)']
N = len(categories)
angles = [n / float(N) * 2 * np.pi for n in range(N)]
angles += angles[:1]

fig, ax = plt.subplots(figsize=(7.5, 7.5), subplot_kw=dict(polar=True), dpi=300)

for m in models_info:
    mid = m['id']
    fm = final_metrics[mid]
    # Normalize each metric scientifically into [50, 90] bounds for clean visualization
    v_map = np.clip((fm['mask_map50_95'] - 0.70) / (0.74 - 0.70) * 40 + 50, 45, 95)
    v_map50 = np.clip((fm['mask_map50'] - 0.88) / (0.94 - 0.88) * 40 + 50, 45, 95)
    v_p = np.clip((fm['precision'] - 0.85) / (0.95 - 0.85) * 40 + 50, 45, 95)
    v_r = np.clip((fm['recall'] - 0.80) / (0.90 - 0.80) * 40 + 50, 45, 95)
    
    # Stability: inverse variance of 10 seeds (higher is more stable)
    inv_var = 1.0 / (fm['mask_map50_95_std']**2)
    v_stab = np.clip((inv_var - 4000) / (18000 - 4000) * 40 + 50, 45, 95)
    
    # Loss Optimization: lower loss is better (val_seg_loss range [1.15, 1.40])
    v_loss = np.clip(((1.40 - fm['val_seg_loss']) / (1.40 - 1.15)) * 40 + 50, 45, 95)
    
    vals = [float(v_map), float(v_map50), float(v_p), float(v_r), float(v_stab), float(v_loss)]
    vals += vals[:1]
    
    ax.plot(angles, vals, linewidth=2.2, linestyle='solid', label=m['label'], color=m['color'])
    ax.fill(angles, vals, color=m['color'], alpha=0.18)

ax.set_theta_offset(np.pi / 2)
ax.set_theta_direction(-1)
ax.set_xticks(angles[:-1])
ax.set_xticklabels(categories, fontsize=10.5, fontweight='bold')
ax.set_ylim(40, 100)
ax.set_yticks([50, 60, 70, 80, 90, 100])
ax.set_yticklabels(['50', '60', '70', '80', '90', '100'], fontsize=9, color='#555555')
plt.title("Đánh Đổi Đa Mục Tiêu (Multi-Objective Radar Profile)\nBaseline vs TSVM trên Bộ Dữ Liệu BG20 (10 Seeds)", fontsize=13, fontweight='bold', pad=22)
plt.legend(loc='upper right', bbox_to_anchor=(1.30, 1.12), frameon=True, fontsize=10)
plt.tight_layout()
p7 = os.path.join(fig_dir, '10_radar_multiobjective_tradeoff.png')
plt.savefig(p7, bbox_inches='tight')
plt.close()
print("Generated:", p7)

# ==============================================================================
# CHART 8: 11_boxplot_variance_stability.png (2 Models - Only Mask mAP@50-95)
# ==============================================================================
fig, ax = plt.subplots(figsize=(7.5, 6.0), dpi=300)

labels_box = [m['label'] for m in models_info]
data_map = [final_metrics[m['id']]['seeds_mAP'] for m in models_info]

bp = ax.boxplot(data_map, patch_artist=True, tick_labels=labels_box, widths=0.45)
for patch, m in zip(bp['boxes'], models_info):
    patch.set_facecolor(m['color'])
    patch.set_alpha(0.75)
    patch.set_edgecolor('black')
    patch.set_linewidth(1.2)
for median in bp['medians']:
    median.set(color='black', linewidth=2.2)
for whisker in bp['whiskers']:
    whisker.set(color='black', linewidth=1.2)
for cap in bp['caps']:
    cap.set(color='black', linewidth=1.2)

# Add jitter points for actual 10 seeds
np.random.seed(42)
for i, vals in enumerate(data_map):
    x_jit = np.random.normal(i + 1, 0.04, size=len(vals))
    ax.scatter(x_jit, vals, color='#222222', alpha=0.75, s=42, zorder=4, edgecolor='white', linewidth=0.5)

# Statistical text card annotations for each model
for i, m in enumerate(models_info):
    mid = m['id']
    mean_v = final_metrics[mid]['mask_map50_95']
    std_v = final_metrics[mid]['mask_map50_95_std']
    med_v = float(np.median(data_map[i]))
    min_v = float(np.min(data_map[i]))
    max_v = float(np.max(data_map[i]))
    text_str = f"Mean: {mean_v:.4f} ± {std_v:.4f}\nMedian: {med_v:.4f}\nMin–Max: [{min_v:.4f}, {max_v:.4f}]"
    ax.text(i + 1, 0.690, text_str, ha='center', va='bottom', fontsize=9.5, fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='#f8f9fa', edgecolor='#cccccc', alpha=0.9))

ax.set_title("Phân Bổ Độ Chính Xác Mask mAP@50-95 Qua 10 Seeds Độc Lập\nKiểm Chứng Tính Ổn Định & Co Hẹp Phương Sai (Baseline vs TSVM)", fontsize=12.5, fontweight='bold', pad=15)
ax.set_ylabel("Mask mAP@50-95", fontsize=11.5, fontweight='bold')
ax.set_ylim(0.685, 0.745)
ax.grid(axis='y', linestyle='--', alpha=0.4)
ax.tick_params(axis='x', labelsize=11)
plt.tight_layout()
p8 = os.path.join(fig_dir, '11_boxplot_variance_stability.png')
plt.savefig(p8, bbox_inches='tight')
plt.close()
print("Generated:", p8)

# ==============================================================================
# CHART 9: 12_confusion_matrix_mean_comparison.png (2 Models)
# ==============================================================================
fig, axes = plt.subplots(1, 2, figsize=(11.5, 5.2), dpi=300)
cms = [
    np.array([
        [final_metrics['Baseline']['TP'] / 127.0, final_metrics['Baseline']['FN'] / 127.0],
        [final_metrics['Baseline']['FP'] / 40.0, final_metrics['Baseline']['TN'] / 40.0]
    ]),
    np.array([
        [final_metrics['TSVM']['TP'] / 127.0, final_metrics['TSVM']['FN'] / 127.0],
        [final_metrics['TSVM']['FP'] / 40.0, final_metrics['TSVM']['TN'] / 40.0]
    ])
]
cm_titles = [
    f"Baseline YOLO26s-seg\nmAP@50-95: {final_metrics['Baseline']['mask_map50_95']:.4f} ± {final_metrics['Baseline']['mask_map50_95_std']:.4f}",
    f"TSVM (Topology-Shape)\nmAP@50-95: {final_metrics['TSVM']['mask_map50_95']:.4f} ± {final_metrics['TSVM']['mask_map50_95_std']:.4f}"
]

for idx, (cm, t, ax) in enumerate(zip(cms, cm_titles, axes)):
    im = ax.imshow(cm, cmap='Blues', vmin=0, vmax=1.0)
    ax.set_title(t, fontsize=11.5, fontweight='bold', pad=10)
    ax.set_xticks([0, 1])
    ax.set_yticks([0, 1])
    ax.set_xticklabels(['polyp', 'background'], fontsize=10.5, fontweight='bold')
    ax.set_yticklabels(['polyp', 'background'], fontsize=10.5, fontweight='bold')
    ax.set_xlabel("Predicted Label", fontsize=11, fontweight='bold')
    ax.set_ylabel("True Label", fontsize=11, fontweight='bold')
    for r in range(2):
        for c in range(2):
            val = cm[r, c]
            txt_color = 'white' if val > 0.5 else 'black'
            ax.text(c, r, f"{val:.2f}", ha='center', va='center', color=txt_color, fontsize=14, fontweight='bold')

fig.subplots_adjust(right=0.88)
cbar_ax = fig.add_axes([0.90, 0.20, 0.02, 0.60])
cbar = fig.colorbar(im, cax=cbar_ax)
cbar.set_label("Tỷ Lệ Chuẩn Hóa (Normalized Rate)", fontsize=10.5)

plt.suptitle("Ma Trận Nhầm Lẫn Chuẩn Hóa Trung Bình 10 Seeds (N = 167 ảnh test)", fontsize=13.5, fontweight='bold', y=0.98)
p9 = os.path.join(fig_dir, '12_confusion_matrix_mean_comparison.png')
plt.savefig(p9, bbox_inches='tight')
plt.close()
print("Generated:", p9)

# ==============================================================================
# CHART 10: 13_confusion_matrix_diff_heatmap.png (2 Models)
# ==============================================================================
plt.figure(figsize=(6.8, 5.8), dpi=300)
diff_cm = cms[1] - cms[0]
im = plt.imshow(diff_cm, cmap='RdBu_r', vmin=-0.15, vmax=0.15)
fn_diff = diff_cm[0, 1]
fp_diff = diff_cm[1, 0]
fn_desc = f"Ô FN Giảm ({fn_diff:+.3f})" if fn_diff <= 0 else f"Ô FN Tăng ({fn_diff:+.3f})"
fp_desc = f"Ô FP Giảm ({fp_diff:+.3f})" if fp_diff <= 0 else f"Ô FP Tăng ({fp_diff:+.3f})"
plt.title(f"Ma Trận Chênh Lệch Hiệu Số (TSVM - Baseline)\n{fn_desc}, {fp_desc}", fontsize=12, fontweight='bold', pad=15)
plt.xticks([0, 1], ['polyp', 'background'], fontsize=10.5, fontweight='bold')
plt.yticks([0, 1], ['polyp', 'background'], fontsize=10.5, fontweight='bold')
plt.xlabel("Predicted Label", fontsize=11, fontweight='bold')
plt.ylabel("True Label", fontsize=11, fontweight='bold')
for r in range(2):
    for c in range(2):
        val = diff_cm[r, c]
        color = 'white' if abs(val) > 0.08 else 'black'
        plt.text(c, r, f"{val:+.3f}", ha='center', va='center', color=color, fontsize=14, fontweight='bold')
cbar = plt.colorbar(im, fraction=0.046, pad=0.04)
cbar.set_label("Độ Lệch Hiệu Số (Delta Rate)", fontsize=10.5)
plt.tight_layout()
p10 = os.path.join(fig_dir, '13_confusion_matrix_diff_heatmap.png')
plt.savefig(p10)
plt.close()
print("Generated:", p10)

# ==============================================================================
# CHART 11: 14_confusion_cells_grouped_barchart.png (2 Models)
# ==============================================================================
plt.figure(figsize=(9.5, 5.8), dpi=300)
cm_cells = ['True Positive (TP)\n[Phát hiện đúng]', 'False Negative (FN)\n[Bỏ sót polyp]', 'False Positive (FP)\n[Báo động giả nền]', 'True Negative (TN)\n[Nhận diện đúng nền]']
x = np.arange(len(cm_cells))
width = 0.35

vals_b = [final_metrics['Baseline'][k] for k in ['TP', 'FN', 'FP', 'TN']]
errs_b = [final_metrics['Baseline'][f'{k}_std'] for k in ['TP', 'FN', 'FP', 'TN']]
vals_t = [final_metrics['TSVM'][k] for k in ['TP', 'FN', 'FP', 'TN']]
errs_t = [final_metrics['TSVM'][f'{k}_std'] for k in ['TP', 'FN', 'FP', 'TN']]

r1 = plt.bar(x - width/2, vals_b, width, yerr=errs_b, capsize=5, label='Baseline YOLO26s-seg', color='#1f77b4', edgecolor='black', alpha=0.88)
r2 = plt.bar(x + width/2, vals_t, width, yerr=errs_t, capsize=5, label='TSVM (Topology-Shape)', color='#ff7f0e', edgecolor='black', alpha=0.88)

for r in r1:
    y = r.get_height()
    plt.text(r.get_x() + r.get_width()/2.0, y + 3, f"{y:.1f}", ha='center', va='bottom', fontsize=9.5, fontweight='bold', color='#1f77b4')
for r in r2:
    y = r.get_height()
    plt.text(r.get_x() + r.get_width()/2.0, y + 3, f"{y:.1f}", ha='center', va='bottom', fontsize=9.5, fontweight='bold', color='#d95f02')

plt.title("So Sánh Số Lượng Các Ô Ma Trận Nhầm Lẫn (Mean ± 1 Std, 10 Seeds)\nTổng Số Mẫu Kiểm Thử N = 167 ảnh (127 Polyp + 40 Background)", fontsize=12.5, fontweight='bold', pad=15)
plt.ylabel("Số lượng ảnh / tổn thương (Mean ± Std)", fontsize=11, fontweight='bold')
plt.ylim(0, 135)
plt.xticks(x, cm_cells, fontsize=10.5, fontweight='bold')
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.legend(frameon=True, fontsize=10.5)
plt.tight_layout()
p11 = os.path.join(fig_dir, '14_confusion_cells_grouped_barchart.png')
plt.savefig(p11)
plt.close()
print("Generated:", p11)

# ==============================================================================
# CHART 12: 07b_pie_head_to_head_winrate.png (2 Models)
# ==============================================================================
plt.figure(figsize=(6.5, 5.5), dpi=300)
base_map = np.array(final_metrics['Baseline']['seeds_mAP'])
tsvm_map = np.array(final_metrics['TSVM']['seeds_mAP'])
tsvm_wins = int(np.sum(tsvm_map > base_map))
base_wins = int(np.sum(base_map > tsvm_map))
labels_pie = [f'TSVM Thắng ({tsvm_wins}/10 Seeds)', f'Baseline Thắng ({base_wins}/10 Seeds)']
sizes = [tsvm_wins, base_wins]
colors_pie = ['#ff7f0e', '#1f77b4']
explode = (0.05, 0)

wedges, texts, autotexts = plt.pie(sizes, explode=explode, labels=labels_pie, colors=colors_pie, autopct='%1.1f%%',
                                  startangle=140, pctdistance=0.75, wedgeprops=dict(width=0.45, edgecolor='white', linewidth=2),
                                  textprops=dict(fontsize=11, fontweight='bold'))
for at in autotexts:
    at.set_color('white')
    at.set_fontsize(12)

plt.title("Tỷ Lệ Thắng Đối Đầu Trực Diện (Head-to-Head Win Rate)\nTheo Mask mAP@50-95 Qua 10 Seeds Độc Lập", fontsize=12.5, fontweight='bold', pad=15)
plt.tight_layout()
p12 = os.path.join(fig_dir, '07b_pie_head_to_head_winrate.png')
plt.savefig(p12)
plt.close()
print("Generated:", p12)

print(f"\nSuccessfully generated 12 template-aligned 300 DPI figures for 2 MODELS in {fig_dir}!")
